### PR TITLE
Added addWeeks() and subWeeks() methods

### PR DESCRIPTION
**Pull request by regatta-ajd**
Fix for https://github.com/regattadev/dates/issues/8

### CODE REVIEW

**Comment by duncan3dc** [comment]
@regatta-ajd This should be ok if you rebase from master now

**Comment by duncan3dc** [comment]
@regatta-ajd Can we have a couple of tests for `subWeeks()` as well?

**Comment by regatta-ajd** [comment]
@duncan3dc 
I've added the extra tests, but still getting a build failure on job-local, any suggestions?

**Comment by duncan3dc** [comment]
@regatta-ajd We don't build this on our servers as travis handles the CI for us, let me see about disabling it

**Comment by duncan3dc** [comment]
@regatta-ajd Thanks :+1:

**Pull request merged**
